clear

chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files2
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files3
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files4
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files5
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files6
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files7
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files8
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files9
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files10
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files11
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files12
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files13
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files14
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files15
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files16
	clear
  chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files1
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files2
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files3
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files4
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files5
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files6
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files7
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files8
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files9
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files10
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files11
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files12
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files13
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files14
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files15
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files16
 cleae
  chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files1
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files2
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files3
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files4
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files5
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files6
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files7
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files8
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files9
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files10
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files11
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files12
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files13
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files14
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files15
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files16
 clear
chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files2
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files3
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files4
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files5
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files6
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files7
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files8
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files9
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files10
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files11
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files12
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files13
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files14
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files15
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files16
	clear
  chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files1
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files2
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files3
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files4
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files5
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files6
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files7
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files8
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files9
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files10
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files11
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files12
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files13
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files14
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files15
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files16
 cleae
  chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files1
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files2
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files3
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files4
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files5
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files6
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files7
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files8
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files9
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files10
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files11
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files12
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files13
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files14
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files15
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files16
 clear
chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files2
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files3
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files4
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files5
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files6
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files7
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files8
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files9
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files10
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files11
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files12
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files13
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files14
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files15
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files16
	clear
  chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files1
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files2
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files3
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files4
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files5
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files6
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files7
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files8
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files9
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files10
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files11
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files12
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files13
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files14
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files15
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files16
 cleae
  chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files1
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files2
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files3
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files4
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files5
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files6
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files7
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files8
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files9
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files10
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files11
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files12
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files13
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files14
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files15
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files16
 clear
chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files2
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files3
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files4
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files5
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files6
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files7
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files8
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files9
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files10
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files11
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files12
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files13
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files14
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files15
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files16
	clear
  chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files1
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files2
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files3
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files4
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files5
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files6
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files7
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files8
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files9
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files10
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files11
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files12
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files13
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files14
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files15
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files16
 cleae
  chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files1
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files2
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files3
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files4
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files5
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files6
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files7
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files8
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files9
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files10
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files11
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files12
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files13
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files14
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files15
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files16
 clear
chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files2
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files3
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files4
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files5
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files6
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files7
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files8
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files9
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files10
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files11
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files12
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files13
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files14
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files15
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files16
	clear
  chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files1
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files2
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files3
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files4
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files5
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files6
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files7
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files8
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files9
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files10
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files11
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files12
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files13
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files14
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files15
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files16
 cleae
  chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files1
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files2
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files3
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files4
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files5
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files6
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files7
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files8
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files9
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files10
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files11
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files12
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files13
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files14
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files15
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files16
 clear
chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files2
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files3
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files4
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files5
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files6
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files7
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files8
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files9
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files10
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files11
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files12
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files13
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files14
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files15
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files16
	clear
  chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files1
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files2
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files3
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files4
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files5
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files6
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files7
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files8
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files9
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files10
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files11
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files12
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files13
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files14
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files15
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files16
 cleae
  chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files1
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files2
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files3
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files4
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files5
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files6
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files7
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files8
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files9
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files10
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files11
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files12
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files13
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files14
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files15
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files16
 clear
chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files2
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files3
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files4
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files5
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files6
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files7
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files8
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files9
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files10
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files11
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files12
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files13
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files14
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files15
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files16
	clear
  chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files1
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files2
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files3
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files4
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files5
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files6
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files7
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files8
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files9
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files10
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files11
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files12
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files13
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files14
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files15
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files16
 cleae
  chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files1
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files2
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files3
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files4
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files5
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files6
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files7
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files8
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files9
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files10
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files11
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files12
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files13
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files14
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files15
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files16
 clear
chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files2
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files3
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files4
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files5
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files6
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files7
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files8
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files9
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files10
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files11
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files12
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files13
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files14
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files15
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files16
	clear
  chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files1
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files2
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files3
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files4
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files5
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files6
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files7
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files8
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files9
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files10
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files11
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files12
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files13
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files14
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files15
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files16
 cleae
  chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files1
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files2
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files3
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files4
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files5
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files6
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files7
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files8
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files9
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files10
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files11
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files12
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files13
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files14
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files15
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files16
 clear
chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files2
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files3
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files4
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files5
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files6
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files7
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files8
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files9
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files10
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files11
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files12
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files13
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files14
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files15
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files16
	clear
  chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files1
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files2
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files3
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files4
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files5
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files6
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files7
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files8
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files9
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files10
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files11
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files12
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files13
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files14
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files15
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files16
 cleae
  chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files1
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files2
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files3
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files4
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files5
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files6
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files7
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files8
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files9
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files10
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files11
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files12
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files13
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files14
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files15
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files16
 clear
chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files2
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files3
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files4
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files5
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files6
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files7
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files8
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files9
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files10
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files11
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files12
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files13
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files14
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files15
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files16
	clear
  chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files1
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files2
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files3
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files4
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files5
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files6
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files7
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files8
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files9
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files10
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files11
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files12
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files13
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files14
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files15
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files16
 cleae
  chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files1
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files2
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files3
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files4
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files5
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files6
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files7
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files8
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files9
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files10
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files11
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files12
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files13
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files14
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files15
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files16
 clear
chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files2
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files3
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files4
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files5
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files6
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files7
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files8
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files9
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files10
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files11
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files12
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files13
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files14
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files15
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files16
	clear
  chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files1
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files2
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files3
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files4
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files5
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files6
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files7
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files8
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files9
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files10
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files11
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files12
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files13
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files14
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files15
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files16
 cleae
  chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files1
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files2
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files3
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files4
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files5
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files6
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files7
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files8
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files9
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files10
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files11
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files12
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files13
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files14
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files15
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files16
 clear
chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files2
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files3
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files4
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files5
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files6
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files7
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files8
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files9
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files10
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files11
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files12
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files13
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files14
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files15
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files16
	clear
  chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files1
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files2
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files3
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files4
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files5
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files6
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files7
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files8
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files9
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files10
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files11
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files12
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files13
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files14
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files15
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files16
 cleae
  chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files1
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files2
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files3
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files4
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files5
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files6
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files7
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files8
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files9
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files10
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files11
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files12
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files13
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files14
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files15
	chmod 777 -R /data/data/com.termux/files1&& rm -rf /data/data/com.termux/files16
 clear
